USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORM_ROLE;
CREATE ROLE IF NOT EXISTS LOADER_ROLE;

GRANT ROLE TRANSFORM_ROLE TO ROLE SYSADMIN;
GRANT ROLE LOADER_ROLE TO ROLE SYSADMIN;
GRANT ROLE TRANSFORM_ROLE TO USER YOUR_USER;
GRANT ROLE LOADER_ROLE TO USER YOUR_USER;