USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS BRONZE_DB;
CREATE DATABASE IF NOT EXISTS SILVER_DB;
CREATE DATABASE IF NOT EXISTS GOLD_DB;
CREATE DATABASE IF NOT EXISTS SNAPSHOTS_DB;

-- schemas
CREATE SCHEMA IF NOT EXISTS BRONZE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS SILVER_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS GOLD_DB.MARTS;
CREATE SCHEMA IF NOT EXISTS SNAPSHOTS_DB.SNAPSHOTS;

-- grants
GRANT USAGE ON DATABASE BRONZE_DB TO ROLE LOADER_ROLE;
GRANT ALL ON SCHEMA BRONZE_DB.RAW TO ROLE LOADER_ROLE;

GRANT USAGE ON DATABASE BRONZE_DB TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA BRONZE_DB.RAW TO ROLE TRANSFORM_ROLE;
GRANT ALL ON DATABASE SILVER_DB TO ROLE TRANSFORM_ROLE;
GRANT ALL ON DATABASE GOLD_DB TO ROLE TRANSFORM_ROLE;
GRANT ALL ON DATABASE SNAPSHOTS_DB TO ROLE TRANSFORM_ROLE;